# Generated by Django 4.2 on 2023-04-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datosPrueba',
            fields=[
                ('idPrueba', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombrePrueba', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcionPrueba', models.CharField(max_length=50, verbose_name='Prueba')),
            ],
        ),
    ]
